[package]
name = "jetstream_admin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-nats = "0.39.0"
clap = { version = "4.5.23", features = ["derive"] }
tokio = { version = "1.42.0", features = ["rt", "macros"] }

[workspace]
